"use client";
import "./globals.css";
import { Inter } from "next/font/google";

import { AppProps } from "next/app";
// import { Provider } from "react-redux";
// import { PersistGate } from "redux-persist/integration/react";
// import { makeStore } from "../redux/store";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { store, persistor } = makeStore();

  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        {/* <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}> */}
        {children}
        {/* </PersistGate>
        </Provider> */}
      </body>
    </html>
  );
}
